export enum BUTTON_VARIANTS_ENUM {
    PRIMARY = 'primary',
    SECONDARY = 'secondary',
    TERTIARY = 'tertiary',
    SUCCESS = 'success',
    DANGER = 'danger',
    WARNING = 'warning',
    PRIMARY_OUTLINED = 'primary-outlined',
    SECONDARY_OUTLINED = 'secondary-outlined',
    TERTIARY_OUTLINED = 'tertiary-outlined',
    SUCCESS_OUTLINED = 'success-outlined',
    DANGER_OUTLINED = 'danger-outlined',
    WARNING_OUTLINED = 'warning-outlined',
}

export enum BUTTON_SIZES_ENUM {
    SMALL = 'small',
    MEDIUM = 'medium',
    LARGE = 'large',
    EXTRA_LARGE = 'extra-large',
}

export enum BUTTON_ICON_POSITIONS_ENUM {
    LEFT = 'left',
    RIGHT = 'right',
}

export const BUTTON_VARIANTS = [
    BUTTON_VARIANTS_ENUM.PRIMARY,
    BUTTON_VARIANTS_ENUM.SECONDARY,
    BUTTON_VARIANTS_ENUM.TERTIARY,
    BUTTON_VARIANTS_ENUM.SUCCESS,
    BUTTON_VARIANTS_ENUM.DANGER,
    BUTTON_VARIANTS_ENUM.WARNING,
    BUTTON_VARIANTS_ENUM.PRIMARY_OUTLINED,
    BUTTON_VARIANTS_ENUM.SECONDARY_OUTLINED,
    BUTTON_VARIANTS_ENUM.TERTIARY_OUTLINED,
    BUTTON_VARIANTS_ENUM.SUCCESS_OUTLINED,
    BUTTON_VARIANTS_ENUM.DANGER_OUTLINED,
    BUTTON_VARIANTS_ENUM.WARNING_OUTLINED,
];

export const BUTTON_SIZES = [
    BUTTON_SIZES_ENUM.SMALL,
    BUTTON_SIZES_ENUM.MEDIUM,
    BUTTON_SIZES_ENUM.LARGE,
    BUTTON_SIZES_ENUM.EXTRA_LARGE,
];

export const BUTTON_ICON_POSITIONS = [
    BUTTON_ICON_POSITIONS_ENUM.LEFT,
    BUTTON_ICON_POSITIONS_ENUM.RIGHT,
];
