name: Feature Request
description: Suggest a new feature or improvement
title: '[FEATURE] '
labels: enhancement
type: feature

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature or improvement! Please fill out the sections below to help us understand your request.

  - type: input
    id: feature_title
    attributes:
      label: Feature Title
      description: Provide a short and descriptive title for the feature request.
      placeholder: Please add classname based styling
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature or improvement you are suggesting.
      placeholder: Describe the feature or improvement in detail
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Explain why this feature is needed and how it will be used.
      placeholder: Describe the use case or problem this feature will solve

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: List any alternative solutions or features

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
      placeholder: Provide additional context or examples
