blank_issues_enabled: false
contact_links:
    - name: Ask a question or discuss a topic
      url: https://github.com/Newton-School/grauity/discussions
      about: Ask questions or discuss with other users in discussions.
