export const ICON_TAGS = {
    'exclamation-circle': ['Alert'],
    'exclamation-triangle': ['Alert'],
    'info-circle': ['Alert'],
    'question-circle': ['Alert'],
    'code-alt': ['Code'],
    code: ['Code'],
    terminal: ['Code'],
    desktop: ['Device'],
    gamepad: ['Device'],
    lamp: ['Device'],
    laptop: ['Device'],
    mobile: ['Device'],
    archive: ['Docs'],
    'bookmark-fill': ['Docs'],
    bookmark: ['Docs'],
    'file-alt': ['Docs'],
    file: ['Docs'],
    'folder-open': ['Docs'],
    folder: ['Docs'],
    'label-fill': ['Docs'],
    label: ['Docs'],
    note: ['Docs'],
    pen: ['Docs'],
    pin: ['Docs'],
    'mic-off': ['Media'],
    mic: ['Media'],
    'pause-circle-fill': ['Media'],
    'pause-circle': ['Media'],
    pause: ['Media'],
    'play-circle-fill': ['Media'],
    'play-circle': ['Media'],
    play: ['Media'],
    'video-off': ['Media'],
    video: ['Media'],
    'volume-maximum': ['Media'],
    'volume-minimum': ['Media'],
    'volume-mute': ['Media'],
    'heart-fill': ['Misc'],
    heart: ['Misc'],
    'lock-close': ['Misc'],
    'lock-open': ['Misc'],
    'message-circle': ['Misc'],
    'message-double-question': ['Misc'],
    'message-square-info': ['Misc'],
    'message-square': ['Misc'],
    milestone: ['Misc'],
    quiz: ['Misc'],
    smiley: ['Misc'],
    'spark-fill': ['Misc'],
    spark: ['Misc'],
    sparkle: ['Misc'],
    target: ['Misc'],
    'check-badge': ['Reward'],
    crown: ['Reward'],
    flag: ['Reward'],
    gift: ['Reward'],
    medal: ['Reward'],
    'star-fill': ['Reward'],
    'star-half-fill': ['Reward'],
    star: ['Reward'],
    trophy: ['Reward'],
    'arrow-double': ['System'],
    'arrow-down': ['System'],
    'arrow-left': ['System'],
    'arrow-right': ['System'],
    'arrow-up': ['System'],
    bin: ['System'],
    'call-end': ['System'],
    'call-start': ['System'],
    'caret-double': ['System'],
    'caret-down': ['System'],
    'caret-left': ['System'],
    'caret-right': ['System'],
    'caret-up': ['System'],
    'check-circle-fill': ['System'],
    'check-circle': ['System'],
    'check-square-fill': ['System'],
    'check-square': ['System'],
    check: ['System'],
    'chevron-double-down': ['System'],
    'chevron-double-left': ['System'],
    'chevron-double-right': ['System'],
    'chevron-double-up': ['System'],
    'chevron-down': ['System'],
    'chevron-left': ['System'],
    'chevron-right': ['System'],
    'chevron-up': ['System'],
    circle: ['System'],
    'close-circle-fill': ['System'],
    'close-circle': ['System'],
    'close-square-fill': ['System'],
    'close-square': ['System'],
    close: ['System'],
    download: ['System'],
    forward: ['System'],
    'grip-hortizontal': ['System'],
    'grip-vertical': ['System'],
    'growth-down': ['System'],
    'growth-up': ['System'],
    home: ['System'],
    'kebab-horizontal': ['System'],
    'kebab-vertical': ['System'],
    link: ['System'],
    list: ['System'],
    load: ['System'],
    maximize: ['System'],
    'menu-grid': ['System'],
    menu: ['System'],
    minimize: ['System'],
    'minus-circle-fill': ['System'],
    'minus-circle': ['System'],
    'minus-square-fill': ['System'],
    'minus-square': ['System'],
    moon: ['System'],
    'new-tab': ['System'],
    'plus-circle-fill': ['System'],
    'plus-circle': ['System'],
    'plus-square-fill': ['System'],
    'plus-square': ['System'],
    plus: ['System'],
    refresh: ['System'],
    reply: ['System'],
    'screenshare-start': ['System'],
    'screenshare-stop': ['System'],
    search: ['System'],
    settings: ['System'],
    signin: ['System'],
    signout: ['System'],
    square: ['System'],
    sun: ['System'],
    upload: ['System'],
    bell: ['Time'],
    'calender-check': ['Time'],
    'calender-plus': ['Time'],
    calender: ['Time'],
    clock: ['Time'],
    rewatch: ['Time'],
    stopwatch: ['Time'],
    bot: ['User'],
    'person-check': ['User'],
    'person-plus': ['User'],
    person: ['User'],
    users: ['User'],
};
export const TAG_ICONS = {
    Alert: [
        'exclamation-circle',
        'exclamation-triangle',
        'info-circle',
        'question-circle',
    ],
    Code: ['code-alt', 'code', 'terminal'],
    Device: ['desktop', 'gamepad', 'lamp', 'laptop', 'mobile'],
    Docs: [
        'archive',
        'bookmark-fill',
        'bookmark',
        'file-alt',
        'file',
        'folder-open',
        'folder',
        'label-fill',
        'label',
        'note',
        'pen',
        'pin',
    ],
    Media: [
        'mic-off',
        'mic',
        'pause-circle-fill',
        'pause-circle',
        'pause',
        'play-circle-fill',
        'play-circle',
        'play',
        'video-off',
        'video',
        'volume-maximum',
        'volume-minimum',
        'volume-mute',
    ],
    Misc: [
        'heart-fill',
        'heart',
        'lock-close',
        'lock-open',
        'message-circle',
        'message-double-question',
        'message-square-info',
        'message-square',
        'milestone',
        'quiz',
        'smiley',
        'spark-fill',
        'spark',
        'sparkle',
        'target',
    ],
    Reward: [
        'check-badge',
        'crown',
        'flag',
        'gift',
        'medal',
        'star-fill',
        'star-half-fill',
        'star',
        'trophy',
    ],
    System: [
        'arrow-double',
        'arrow-down',
        'arrow-left',
        'arrow-right',
        'arrow-up',
        'bin',
        'call-end',
        'call-start',
        'caret-double',
        'caret-down',
        'caret-left',
        'caret-right',
        'caret-up',
        'check-circle-fill',
        'check-circle',
        'check-square-fill',
        'check-square',
        'check',
        'chevron-double-down',
        'chevron-double-left',
        'chevron-double-right',
        'chevron-double-up',
        'chevron-down',
        'chevron-left',
        'chevron-right',
        'chevron-up',
        'circle',
        'close-circle-fill',
        'close-circle',
        'close-square-fill',
        'close-square',
        'close',
        'download',
        'forward',
        'grip-hortizontal',
        'grip-vertical',
        'growth-down',
        'growth-up',
        'home',
        'kebab-horizontal',
        'kebab-vertical',
        'link',
        'list',
        'load',
        'maximize',
        'menu-grid',
        'menu',
        'minimize',
        'minus-circle-fill',
        'minus-circle',
        'minus-square-fill',
        'minus-square',
        'moon',
        'new-tab',
        'plus-circle-fill',
        'plus-circle',
        'plus-square-fill',
        'plus-square',
        'plus',
        'refresh',
        'reply',
        'screenshare-start',
        'screenshare-stop',
        'search',
        'settings',
        'signin',
        'signout',
        'square',
        'sun',
        'upload',
    ],
    Time: [
        'bell',
        'calender-check',
        'calender-plus',
        'calender',
        'clock',
        'rewatch',
        'stopwatch',
    ],
    User: ['bot', 'person-check', 'person-plus', 'person', 'users'],
};
