# This workflow will build storybook pages when a pull request or a commit is made to the master branch

name: Build Storybook

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    submodules: recursive
            -   uses: actions/setup-node@v3
                with:
                    node-version: 20
            -   run: npm run build-storybook
